=== SachinDuplicate/XML-FIFA/19033712_russiandoll.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="schema">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="worldcup">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="FifaWorldcup" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
					<xs:element type="xs:string" name="Title"/>
                    <xs:element type="xs:string" name="Organizer"/>
					<xs:element type="xs:string" name="totalTeam"/>
					<xs:element type="xs:string" name="ticketPrice"/>               
                    <xs:element name="contact">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="country"/>
                          <xs:element type="xs:string" name="URL"/>                    
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
				  <xs:attribute type="xs:string" name="info" use="optional"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="matchList">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Matches">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="match" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:string" name="Group"/>
								<xs:element type="xs:string" name="Knockout" minOccurs="0"/>
								<xs:element type="xs:string" name="quater-final" minOccurs="0"/>
								<xs:element type="xs:string" name="semi-final" minOccurs="0"/>
								<xs:element type="xs:string" name="Finalist" minOccurs="0"/>
								<xs:element type="xs:string" name="Winner" minOccurs="0"/>
								<xs:element type="xs:string" name="Runner-up" minOccurs="0"/>
								<xs:element type="xs:string" name="Play-off" minOccurs="0"/>
								<xs:element type="xs:string" name="Third" minOccurs="0"/>
								<xs:element type="xs:string" name="Golden-Ball" minOccurs="0"/>
								<xs:element type="xs:string" name="Golden-Boot" minOccurs="0"/>
								<xs:element type="xs:string" name="Golden-Glove" minOccurs="0"/>
								<xs:element type="xs:string" name="Best-Young-Player" minOccurs="0"/>
								<xs:element type="xs:string" name="Fair-Play" minOccurs="0"/>
                              </xs:sequence>
                              <xs:attribute type="xs:string" name="type" use="optional"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
					 </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== SachinDuplicate/XML-FIFA/19033712_fifa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="19033712_russiandoll.xsd"-->
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="19033712_venetianblind.xsd">
<!--schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="19033712_flatcatalog.xsd"-->
<!--DOCTYPE worldcup SYSTEM "19033712_worldcup.dtd"-->	
	<worldcup>
		<FifaWorldcup info ="Details">
			<Title> FIFA Worldcup 2018 </Title>
			<Organizer> 18030800 worldcup </Organizer>
			<totalTeam> 32 </totalTeam>
			<ticketPrice> USD 210-1100 </ticketPrice>

		<contact>
			<country> Russia </country>
			<URL> https://www.fifa.com/contact </URL>
		</contact>
		</FifaWorldcup>

		<matchList>
			<Matches>
				<match type ="Phases, FinalStanding, Awards">
					<Group> 48 </Group>
					<Knockout> 8 </Knockout>
					<quater-final> 4 </quater-final>
					<semi-final> 2 </semi-final>
					<Finalist> France vs Croatia </Finalist>
					<Winner> France </Winner>
					<Runner-up> Croatia </Runner-up>
					<Play-off> Belgium vs England </Play-off>
					<Third> Belgium </Third>
					<Golden-Ball> Luka Modric </Golden-Ball>
					<Golden-Boot> Harry Kane </Golden-Boot>
					<Golden-Glove> Thibaut Courtois </Golden-Glove>
					<Best-Young-Player> Kylian Mbappe </Best-Young-Player>
					<Fair-Play> Spain </Fair-Play>
				</match>
			</Matches>
		</matchList>
	</worldcup>
</schema>
